/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.seatecnologia.treinamento.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Modelo service. Represents a row in the &quot;agenciamodelos_Modelo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.seatecnologia.treinamento.model.impl.ModeloModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.seatecnologia.treinamento.model.impl.ModeloImpl}.
 * </p>
 *
 * @author felipearaujo
 * @see Modelo
 * @see br.com.seatecnologia.treinamento.model.impl.ModeloImpl
 * @see br.com.seatecnologia.treinamento.model.impl.ModeloModelImpl
 * @generated
 */
public interface ModeloModel extends BaseModel<Modelo>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a modelo model instance should use the {@link Modelo} interface instead.
	 */

	/**
	 * Returns the primary key of this modelo.
	 *
	 * @return the primary key of this modelo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this modelo.
	 *
	 * @param primaryKey the primary key of this modelo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the modelo ID of this modelo.
	 *
	 * @return the modelo ID of this modelo
	 */
	public long getModeloId();

	/**
	 * Sets the modelo ID of this modelo.
	 *
	 * @param modeloId the modelo ID of this modelo
	 */
	public void setModeloId(long modeloId);

	/**
	 * Returns the group ID of this modelo.
	 *
	 * @return the group ID of this modelo
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this modelo.
	 *
	 * @param groupId the group ID of this modelo
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this modelo.
	 *
	 * @return the company ID of this modelo
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this modelo.
	 *
	 * @param companyId the company ID of this modelo
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this modelo.
	 *
	 * @return the user ID of this modelo
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this modelo.
	 *
	 * @param userId the user ID of this modelo
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this modelo.
	 *
	 * @return the user uuid of this modelo
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this modelo.
	 *
	 * @param userUuid the user uuid of this modelo
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this modelo.
	 *
	 * @return the user name of this modelo
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this modelo.
	 *
	 * @param userName the user name of this modelo
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this modelo.
	 *
	 * @return the create date of this modelo
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this modelo.
	 *
	 * @param createDate the create date of this modelo
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this modelo.
	 *
	 * @return the modified date of this modelo
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this modelo.
	 *
	 * @param modifiedDate the modified date of this modelo
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this modelo.
	 *
	 * @return the nome of this modelo
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this modelo.
	 *
	 * @param nome the nome of this modelo
	 */
	public void setNome(String nome);

	/**
	 * Returns the idade of this modelo.
	 *
	 * @return the idade of this modelo
	 */
	public int getIdade();

	/**
	 * Sets the idade of this modelo.
	 *
	 * @param idade the idade of this modelo
	 */
	public void setIdade(int idade);

	/**
	 * Returns the altura of this modelo.
	 *
	 * @return the altura of this modelo
	 */
	public double getAltura();

	/**
	 * Sets the altura of this modelo.
	 *
	 * @param altura the altura of this modelo
	 */
	public void setAltura(double altura);

	/**
	 * Returns the peso of this modelo.
	 *
	 * @return the peso of this modelo
	 */
	public double getPeso();

	/**
	 * Sets the peso of this modelo.
	 *
	 * @param peso the peso of this modelo
	 */
	public void setPeso(double peso);

	/**
	 * Returns the etinia of this modelo.
	 *
	 * @return the etinia of this modelo
	 */
	public int getEtinia();

	/**
	 * Sets the etinia of this modelo.
	 *
	 * @param etinia the etinia of this modelo
	 */
	public void setEtinia(int etinia);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(br.com.seatecnologia.treinamento.model.Modelo modelo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.seatecnologia.treinamento.model.Modelo> toCacheModel();

	@Override
	public br.com.seatecnologia.treinamento.model.Modelo toEscapedModel();

	@Override
	public br.com.seatecnologia.treinamento.model.Modelo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}